// Wallet construction and funding for the end-to-end run.
//
// SPDX-License-Identifier: Apache-2.0
//
// Adapted from midnightntwrk/midnight-local-dev (`src/wallet.ts`) and
// midnightntwrk/example-bboard (`bboard-cli/src/midnight-wallet-provider.ts`),
// both Apache-2.0. The sync, funding and DUST-registration sequence is theirs;
// the surrounding structure is ours.
//
// Nothing here is specific to QuietBooks. It exists because a transaction on
// Midnight cannot be submitted without DUST, DUST is only generated by
// registered NIGHT, and a freshly built wallet has neither. Getting that wrong
// produces a timeout rather than an error, so the waits below are explicit and
// each one says what it is waiting for.

import {
  DustSecretKey,
  LedgerParameters,
  nativeToken,
  ZswapSecretKeys,
  type CoinPublicKey,
  type EncPublicKey,
  type FinalizedTransaction,
  type SyntheticCost,
} from '@midnight-ntwrk/midnight-js-protocol/ledger';
import type {
  MidnightProvider,
  UnboundTransaction,
  WalletProvider,
} from '@midnight-ntwrk/midnight-js-types';
import { ttlOneHour } from '@midnight-ntwrk/midnight-js-utils';
import {
  FluentWalletBuilder,
  type DustWalletOptions,
  type EnvironmentConfiguration,
} from '@midnight-ntwrk/testkit-js';
import type { WalletFacade, FacadeState, UnshieldedKeystore } from '@midnight-ntwrk/wallet-sdk';
import {
  ShieldedAddress,
  ShieldedCoinPublicKey,
  ShieldedEncryptionPublicKey,
  type UnshieldedAddress,
} from '@midnight-ntwrk/wallet-sdk-address-format';
import * as Rx from 'rxjs';
import type { Logger } from 'pino';

// The indexer client subscribes over WebSocket and reaches for the global
// implementation. Node has provided one since 22, which this package requires,
// so nothing needs polyfilling. Asserting it here turns a missing global into a
// clear message instead of a failure deep inside Apollo's transport.
if (typeof globalThis.WebSocket !== 'function') {
  throw new Error(
    'quietbooks: no global WebSocket. Node 22 or newer is required to reach the indexer.',
  );
}

const DUST_OPTIONS: DustWalletOptions = {
  ledgerParams: LedgerParameters.initialParameters(),
  // This is the value midnight-local-dev uses against this same node image.
  //
  // This comment used to claim more than that, and the claim was wrong. It said
  // the overhead must not be larger, because the bboard CLI's 5e17 is a thousand
  // times the genesis wallet's 5e14 NIGHT and made every transaction unfundable
  // with a bare "Transaction submission error". Measured since, both ways,
  // against this node: a deploy through the same wallet path succeeds at 1000
  // and succeeds at 5e17. The overhead was never the problem.
  //
  // What produces that error is a wallet whose DUST is not yet spendable --
  // fees are paid in DUST, which registered NIGHT generates over a few blocks,
  // so a deploy submitted before `registerForDust` has settled fails exactly
  // that way. Lowering the overhead and fixing the sync happened together, and
  // the wrong one got written down as the cause.
  //
  // Left at 1000 because it is what midnight-local-dev uses and it works; the
  // reason to prefer it is no longer a claim about the other value being broken.
  // Recorded at length because a wrong explanation is worse than none: reasoning
  // from this one nearly produced a "fix" to the CLI, which sets 5e17 and is
  // fine.
  additionalFeeOverhead: 1_000n,
  feeBlocksMargin: 5,
};

export type WalletContext = {
  readonly wallet: WalletFacade;
  readonly shieldedSecretKeys: ZswapSecretKeys;
  readonly dustSecretKey: DustSecretKey;
  readonly unshieldedKeystore: UnshieldedKeystore;
};

const isComplete = (progress: unknown): boolean => {
  if (progress === null || typeof progress !== 'object') return false;
  const fn = (progress as { isStrictlyComplete?: unknown }).isStrictlyComplete;
  return typeof fn === 'function' && (fn as () => boolean).call(progress);
};

export const buildWallet = async (
  env: EnvironmentConfiguration,
  seed: string,
): Promise<WalletContext> => {
  const { wallet, seeds, keystore } = await FluentWalletBuilder.forEnvironment(env)
    .withDustOptions(DUST_OPTIONS)
    .withSeed(seed)
    .buildWithoutStarting();

  const shieldedSecretKeys = ZswapSecretKeys.fromSeed(seeds.shielded);
  const dustSecretKey = DustSecretKey.fromSeed(seeds.dust);
  await wallet.start(shieldedSecretKeys, dustSecretKey);

  return { wallet, shieldedSecretKeys, dustSecretKey, unshieldedKeystore: keystore };
};

/** Block until all three sub-wallets have caught up with the chain. */
export const waitForSync = (
  ctx: WalletContext,
  logger: Logger,
  timeoutMs = 300_000,
): Promise<FacadeState> =>
  Rx.firstValueFrom(
    ctx.wallet.state().pipe(
      Rx.throttleTime(4_000, undefined, { leading: true, trailing: true }),
      Rx.tap((s) =>
        logger.info(
          `sync shielded=${isComplete(s.shielded.state.progress)} ` +
            `unshielded=${isComplete(s.unshielded.progress)} ` +
            `dust=${isComplete(s.dust.state.progress)}`,
        ),
      ),
      Rx.filter(
        (s) =>
          isComplete(s.shielded.state.progress) &&
          isComplete(s.unshielded.progress) &&
          isComplete(s.dust.state.progress),
      ),
      Rx.timeout({
        each: timeoutMs,
        with: () =>
          Rx.throwError(
            () =>
              new Error(
                `wallet did not finish syncing within ${timeoutMs}ms. Is the indexer running and caught up?`,
              ),
          ),
      }),
    ),
  );

/** Block until the wallet can see NIGHT. */
export const waitForFunds = (
  ctx: WalletContext,
  logger: Logger,
  timeoutMs = 300_000,
): Promise<bigint> =>
  Rx.firstValueFrom(
    ctx.wallet.state().pipe(
      Rx.throttleTime(4_000, undefined, { leading: true, trailing: true }),
      Rx.map(
        (s) =>
          (s.unshielded?.balances[nativeToken().raw] ?? 0n) +
          (s.shielded?.balances[nativeToken().raw] ?? 0n),
      ),
      Rx.withLatestFrom(ctx.wallet.state()),
      // The split matters, not just the total. Escrow hands the contract a
      // shielded coin, so a wallet holding only unshielded NIGHT can pay fees
      // and still fail to fund an escrow -- and the failure surfaces deep inside
      // balancing rather than at the point the funds were checked.
      Rx.tap(([balance, s]) =>
        logger.info(
          `NIGHT balance: ${balance} ` +
            `(unshielded ${s.unshielded?.balances[nativeToken().raw] ?? 0n}, ` +
            `shielded ${s.shielded?.balances[nativeToken().raw] ?? 0n})`,
        ),
      ),
      Rx.map(([balance]) => balance),
      Rx.filter((balance) => balance > 0n),
      Rx.timeout({
        each: timeoutMs,
        with: () =>
          Rx.throwError(
            () =>
              new Error(
                `wallet received no NIGHT within ${timeoutMs}ms. On the undeployed preset the ` +
                  'genesis seed holds the minted supply; any other seed starts empty.',
              ),
          ),
      }),
    ),
  );

const waitForSpendableDust = (ctx: WalletContext, logger: Logger, timeoutMs = 300_000) =>
  Rx.firstValueFrom(
    ctx.wallet.state().pipe(
      Rx.throttleTime(4_000, undefined, { leading: true, trailing: true }),
      Rx.tap((s) => logger.info(`spendable DUST coins: ${s.dust?.availableCoins.length ?? 0}`)),
      Rx.filter((s) => (s.dust?.availableCoins.length ?? 0) >= 1),
      Rx.timeout({
        each: timeoutMs,
        with: () =>
          Rx.throwError(() => new Error(`no spendable DUST appeared within ${timeoutMs}ms`)),
      }),
    ),
  );

/**
 * Register NIGHT for DUST generation, and wait until DUST is actually spendable.
 *
 * Fees are paid in DUST, which NIGHT generates only once its UTXOs are
 * registered. Skipping the wait at the end is the classic mistake: registration
 * is accepted immediately but the first DUST coin takes a few blocks, and a
 * transaction submitted in between fails for lack of fees.
 */
export const registerForDust = async (ctx: WalletContext, logger: Logger): Promise<void> => {
  const state = await Rx.firstValueFrom(
    ctx.wallet.state().pipe(Rx.filter((s) => isComplete(s.unshielded.progress))),
  );

  const unregistered =
    state.unshielded?.availableCoins.filter(
      (coin) => coin.meta.registeredForDustGeneration === false,
    ) ?? [];

  if (unregistered.length === 0) {
    if ((state.dust?.availableCoins.length ?? 0) >= 1) {
      logger.info('DUST already spendable');
      return;
    }
    await waitForSpendableDust(ctx, logger);
    return;
  }

  logger.info(`registering ${unregistered.length} NIGHT UTXO(s) for DUST generation`);
  const recipe = await ctx.wallet.registerNightUtxosForDustGeneration(
    unregistered,
    ctx.unshieldedKeystore.getPublicKey(),
    (payload) => ctx.unshieldedKeystore.signData(payload),
  );
  const finalized = await ctx.wallet.finalizeRecipe(recipe);
  const txId = await ctx.wallet.submitTransaction(finalized);
  logger.info(`DUST registration submitted: ${txId}`);

  await waitForSpendableDust(ctx, logger);
  logger.info('DUST is spendable');
};

const COST_DIMENSIONS = [
  'readTime',
  'computeTime',
  'blockUsage',
  'bytesWritten',
  'bytesChurned',
] as const satisfies readonly (keyof SyntheticCost)[];

/**
 * Where a wallet receives money, in both forms the ledger has.
 *
 * A shielded address is the coin public key and the encryption public key
 * together, which is why paying a stranger needs both: the first says which
 * output is theirs, the second is what the ciphertext beside it is built for.
 * The unshielded address the wallet already tracks in its own state.
 */
export const addressesOf = async (
  ctx: WalletContext,
): Promise<{ shielded: ShieldedAddress; unshielded: UnshieldedAddress }> => {
  const state = await Rx.firstValueFrom(
    ctx.wallet.state().pipe(Rx.filter((s) => s.unshielded !== undefined)),
  );
  return {
    shielded: new ShieldedAddress(
      ShieldedCoinPublicKey.fromHexString(ctx.shieldedSecretKeys.coinPublicKey),
      ShieldedEncryptionPublicKey.fromHexString(ctx.shieldedSecretKeys.encryptionPublicKey),
    ),
    unshielded: state.unshielded.address,
  };
};

/**
 * Move NIGHT from one wallet to another and wait for the recipient to see it.
 *
 * On the `undeployed` preset the genesis seed holds the entire minted supply and
 * every other seed starts empty, so a second party has to be funded from the
 * first before it can do anything. There is no faucet to ask.
 *
 * Both forms are sent. A wallet holding only unshielded NIGHT can pay fees and
 * still fail to fund an escrow or a shielded settlement, and that failure
 * surfaces deep inside balancing rather than at the point the funds were
 * checked -- the same trap `waitForFunds` logs the split for.
 *
 * The recipient is registered for DUST afterwards, because unregistered NIGHT
 * generates none and fees are paid in DUST. A transfer that lands and a wallet
 * that cannot spend look identical until the first transaction fails.
 */
export const fundWallet = async (
  from: WalletContext,
  to: WalletContext,
  logger: Logger,
  amounts: { shielded: bigint; unshielded: bigint },
): Promise<bigint> => {
  const { shielded, unshielded } = await addressesOf(to);
  const night = nativeToken().raw;

  logger.info(
    `funding ${unshielded.hexString.slice(0, 16)}.. with ` +
      `${amounts.unshielded} unshielded and ${amounts.shielded} shielded NIGHT`,
  );

  const recipe = await from.wallet.transferTransaction(
    [
      {
        type: 'unshielded',
        outputs: [{ type: night, receiverAddress: unshielded, amount: amounts.unshielded }],
      },
      {
        type: 'shielded',
        outputs: [{ type: night, receiverAddress: shielded, amount: amounts.shielded }],
      },
    ],
    { shieldedSecretKeys: from.shieldedSecretKeys, dustSecretKey: from.dustSecretKey },
    { ttl: ttlOneHour(), payFees: true },
  );

  const signed = await from.wallet.signRecipe(recipe, (payload) =>
    from.unshieldedKeystore.signData(payload),
  );
  const id = await from.wallet.submitTransaction(await from.wallet.finalizeRecipe(signed));
  logger.info(`funding transaction ${id}`);

  const balance = await waitForFunds(to, logger);
  await registerForDust(to, logger);
  return balance;
};

/**
 * The block limit for each cost dimension, in that dimension's own units.
 *
 * The ledger does not expose the limits directly. It exposes
 * `normalizeFullness`, which divides a cost by the limits and throws if any
 * dimension exceeds 1. Feeding it a unit vector -- one dimension set to a known
 * value, the rest zero -- therefore returns that dimension's fraction of its
 * limit, and the limit is the value divided by the fraction.
 *
 * This is derived rather than hardcoded so it stays correct if the parameters
 * change.
 */
export const blockLimits = (params: LedgerParameters): Record<string, bigint> => {
  const limits: Record<string, bigint> = {};

  for (const dimension of COST_DIMENSIONS) {
    const unit = (value: bigint): SyntheticCost =>
      Object.fromEntries(
        COST_DIMENSIONS.map((d) => [d, d === dimension ? value : 0n]),
      ) as unknown as SyntheticCost;

    const fractionAt = (value: bigint): number | undefined => {
      try {
        return params.normalizeFullness(unit(value))[dimension];
      } catch {
        return undefined;
      }
    };

    // Climb until the probe is rejected, keeping the last accepted value. The
    // limits differ by many orders of magnitude between dimensions -- picoseconds
    // of compute against bytes of blockspace -- so a fixed probe cannot serve
    // all five.
    let accepted = 0n;
    let probe = 1n;
    while (probe < 1n << 60n) {
      if (fractionAt(probe) === undefined) break;
      accepted = probe;
      probe *= 2n;
    }

    const fraction = accepted > 0n ? fractionAt(accepted) : undefined;
    limits[dimension] =
      fraction !== undefined && fraction > 0
        ? BigInt(Math.round(Number(accepted) / fraction))
        : 0n;
  }

  return limits;
};

/**
 * Describe a transaction's cost as a percentage of each block limit.
 *
 * A node rejects an oversized transaction with nothing but
 * "1010: Transaction would exhaust the block limits", which does not say which
 * limit or by how much. This says both.
 */
export const describeCost = (tx: FinalizedTransaction, params: LedgerParameters): string => {
  const cost = tx.cost(params);
  const limits = blockLimits(params);
  const parts = [`serialized=${tx.serialize().length}B`, ...COST_DIMENSIONS.map((dimension) => {
    const used = cost[dimension];
    const limit = limits[dimension] ?? 0n;
    if (limit === 0n) return `${dimension}=${used} (limit unknown)`;
    const percent = (Number(used) / Number(limit)) * 100;
    return `${dimension}=${used}/${limit} (${percent.toFixed(1)}%)`;
  })];
  return parts.join('  ');
};

/** The dimensions this transaction exceeds, empty if it fits in a block. */
export const overBlockLimit = (tx: FinalizedTransaction, params: LedgerParameters): string[] => {
  const cost = tx.cost(params);
  const limits = blockLimits(params);
  return COST_DIMENSIONS.filter((dimension) => {
    const limit = limits[dimension] ?? 0n;
    return limit > 0n && cost[dimension] > limit;
  });
};

/** Adapter satisfying midnight-js's wallet and submission interfaces. */
export class E2EWalletProvider implements WalletProvider, MidnightProvider {
  constructor(
    private readonly ctx: WalletContext,
    private readonly logger: Logger,
  ) {}

  getCoinPublicKey(): CoinPublicKey {
    return this.ctx.shieldedSecretKeys.coinPublicKey;
  }

  getEncryptionPublicKey(): EncPublicKey {
    return this.ctx.shieldedSecretKeys.encryptionPublicKey;
  }

  async balanceTx(tx: UnboundTransaction, ttl: Date = ttlOneHour()): Promise<FinalizedTransaction> {
    const recipe = await this.ctx.wallet.balanceUnboundTransaction(
      tx,
      {
        shieldedSecretKeys: this.ctx.shieldedSecretKeys,
        dustSecretKey: this.ctx.dustSecretKey,
      },
      { ttl },
    );
    const signed = await this.ctx.wallet.signRecipe(recipe, (payload) =>
      this.ctx.unshieldedKeystore.signData(payload),
    );
    return this.ctx.wallet.finalizeRecipe(signed);
  }

  async submitTx(tx: FinalizedTransaction): Promise<string> {
    const params = LedgerParameters.initialParameters();
    this.logger.info(`transaction cost: ${describeCost(tx, params)}`);

    const exceeded = overBlockLimit(tx, params);
    if (exceeded.length > 0) {
      // The node would reject this with an opaque RPC code. Saying which
      // dimension is over, before submitting, is the difference between a
      // report that is actionable and one that is not.
      throw new Error(
        `transaction exceeds the block limit on ${exceeded.join(', ')}. ` +
          `Cost: ${describeCost(tx, params)}`,
      );
    }

    const id = await this.ctx.wallet.submitTransaction(tx);
    this.logger.info(`submitted ${id}`);
    return id;
  }
}
