// Wallet construction and funding for the end-to-end run.
//
// SPDX-License-Identifier: Apache-2.0
//
// Adapted from midnightntwrk/midnight-local-dev (`src/wallet.ts`) and
// midnightntwrk/example-bboard (`bboard-cli/src/midnight-wallet-provider.ts`),
// both Apache-2.0. The sync, funding and DUST-registration sequence is theirs;
// the surrounding structure is ours.
//
// Nothing here is specific to QuietBooks. It exists because a transaction on
// Midnight cannot be submitted without DUST, DUST is only generated by
// registered NIGHT, and a freshly built wallet has neither. Getting that wrong
// produces a timeout rather than an error, so the waits below are explicit and
// each one says what it is waiting for.

import {
  DustSecretKey,
  LedgerParameters,
  nativeToken,
  ZswapSecretKeys,
  type CoinPublicKey,
  type EncPublicKey,
  type FinalizedTransaction,
} from '@midnight-ntwrk/midnight-js-protocol/ledger';
import type {
  MidnightProvider,
  UnboundTransaction,
  WalletProvider,
} from '@midnight-ntwrk/midnight-js-types';
import { ttlOneHour } from '@midnight-ntwrk/midnight-js-utils';
import {
  FluentWalletBuilder,
  type DustWalletOptions,
  type EnvironmentConfiguration,
} from '@midnight-ntwrk/testkit-js';
import type { WalletFacade, FacadeState, UnshieldedKeystore } from '@midnight-ntwrk/wallet-sdk';
import * as Rx from 'rxjs';
import type { Logger } from 'pino';

// The indexer client subscribes over WebSocket and reaches for the global
// implementation. Node has provided one since 22, which this package requires,
// so nothing needs polyfilling. Asserting it here turns a missing global into a
// clear message instead of a failure deep inside Apollo's transport.
if (typeof globalThis.WebSocket !== 'function') {
  throw new Error(
    'quietbooks: no global WebSocket. Node 22 or newer is required to reach the indexer.',
  );
}

const DUST_OPTIONS: DustWalletOptions = {
  ledgerParams: LedgerParameters.initialParameters(),
  // The undeployed preset prices fees differently from a public network. This
  // margin is what midnight-local-dev uses against the same node image.
  additionalFeeOverhead: 500_000_000_000_000_000n,
  feeBlocksMargin: 5,
};

export type WalletContext = {
  readonly wallet: WalletFacade;
  readonly shieldedSecretKeys: ZswapSecretKeys;
  readonly dustSecretKey: DustSecretKey;
  readonly unshieldedKeystore: UnshieldedKeystore;
};

const isComplete = (progress: unknown): boolean => {
  if (progress === null || typeof progress !== 'object') return false;
  const fn = (progress as { isStrictlyComplete?: unknown }).isStrictlyComplete;
  return typeof fn === 'function' && (fn as () => boolean).call(progress);
};

export const buildWallet = async (
  env: EnvironmentConfiguration,
  seed: string,
): Promise<WalletContext> => {
  const { wallet, seeds, keystore } = await FluentWalletBuilder.forEnvironment(env)
    .withDustOptions(DUST_OPTIONS)
    .withSeed(seed)
    .buildWithoutStarting();

  const shieldedSecretKeys = ZswapSecretKeys.fromSeed(seeds.shielded);
  const dustSecretKey = DustSecretKey.fromSeed(seeds.dust);
  await wallet.start(shieldedSecretKeys, dustSecretKey);

  return { wallet, shieldedSecretKeys, dustSecretKey, unshieldedKeystore: keystore };
};

/** Block until all three sub-wallets have caught up with the chain. */
export const waitForSync = (
  ctx: WalletContext,
  logger: Logger,
  timeoutMs = 300_000,
): Promise<FacadeState> =>
  Rx.firstValueFrom(
    ctx.wallet.state().pipe(
      Rx.throttleTime(4_000, undefined, { leading: true, trailing: true }),
      Rx.tap((s) =>
        logger.info(
          `sync shielded=${isComplete(s.shielded.state.progress)} ` +
            `unshielded=${isComplete(s.unshielded.progress)} ` +
            `dust=${isComplete(s.dust.state.progress)}`,
        ),
      ),
      Rx.filter(
        (s) =>
          isComplete(s.shielded.state.progress) &&
          isComplete(s.unshielded.progress) &&
          isComplete(s.dust.state.progress),
      ),
      Rx.timeout({
        each: timeoutMs,
        with: () =>
          Rx.throwError(
            () =>
              new Error(
                `wallet did not finish syncing within ${timeoutMs}ms. Is the indexer running and caught up?`,
              ),
          ),
      }),
    ),
  );

/** Block until the wallet can see NIGHT. */
export const waitForFunds = (
  ctx: WalletContext,
  logger: Logger,
  timeoutMs = 300_000,
): Promise<bigint> =>
  Rx.firstValueFrom(
    ctx.wallet.state().pipe(
      Rx.throttleTime(4_000, undefined, { leading: true, trailing: true }),
      Rx.map(
        (s) =>
          (s.unshielded?.balances[nativeToken().raw] ?? 0n) +
          (s.shielded?.balances[nativeToken().raw] ?? 0n),
      ),
      Rx.tap((balance) => logger.info(`NIGHT balance: ${balance}`)),
      Rx.filter((balance) => balance > 0n),
      Rx.timeout({
        each: timeoutMs,
        with: () =>
          Rx.throwError(
            () =>
              new Error(
                `wallet received no NIGHT within ${timeoutMs}ms. On the undeployed preset the ` +
                  'genesis seed holds the minted supply; any other seed starts empty.',
              ),
          ),
      }),
    ),
  );

const waitForSpendableDust = (ctx: WalletContext, logger: Logger, timeoutMs = 300_000) =>
  Rx.firstValueFrom(
    ctx.wallet.state().pipe(
      Rx.throttleTime(4_000, undefined, { leading: true, trailing: true }),
      Rx.tap((s) => logger.info(`spendable DUST coins: ${s.dust?.availableCoins.length ?? 0}`)),
      Rx.filter((s) => (s.dust?.availableCoins.length ?? 0) >= 1),
      Rx.timeout({
        each: timeoutMs,
        with: () =>
          Rx.throwError(() => new Error(`no spendable DUST appeared within ${timeoutMs}ms`)),
      }),
    ),
  );

/**
 * Register NIGHT for DUST generation, and wait until DUST is actually spendable.
 *
 * Fees are paid in DUST, which NIGHT generates only once its UTXOs are
 * registered. Skipping the wait at the end is the classic mistake: registration
 * is accepted immediately but the first DUST coin takes a few blocks, and a
 * transaction submitted in between fails for lack of fees.
 */
export const registerForDust = async (ctx: WalletContext, logger: Logger): Promise<void> => {
  const state = await Rx.firstValueFrom(
    ctx.wallet.state().pipe(Rx.filter((s) => isComplete(s.unshielded.progress))),
  );

  const unregistered =
    state.unshielded?.availableCoins.filter(
      (coin) => coin.meta.registeredForDustGeneration === false,
    ) ?? [];

  if (unregistered.length === 0) {
    if ((state.dust?.availableCoins.length ?? 0) >= 1) {
      logger.info('DUST already spendable');
      return;
    }
    await waitForSpendableDust(ctx, logger);
    return;
  }

  logger.info(`registering ${unregistered.length} NIGHT UTXO(s) for DUST generation`);
  const recipe = await ctx.wallet.registerNightUtxosForDustGeneration(
    unregistered,
    ctx.unshieldedKeystore.getPublicKey(),
    (payload) => ctx.unshieldedKeystore.signData(payload),
  );
  const finalized = await ctx.wallet.finalizeRecipe(recipe);
  const txId = await ctx.wallet.submitTransaction(finalized);
  logger.info(`DUST registration submitted: ${txId}`);

  await waitForSpendableDust(ctx, logger);
  logger.info('DUST is spendable');
};

/** Adapter satisfying midnight-js's wallet and submission interfaces. */
export class E2EWalletProvider implements WalletProvider, MidnightProvider {
  constructor(
    private readonly ctx: WalletContext,
    private readonly logger: Logger,
  ) {}

  getCoinPublicKey(): CoinPublicKey {
    return this.ctx.shieldedSecretKeys.coinPublicKey;
  }

  getEncryptionPublicKey(): EncPublicKey {
    return this.ctx.shieldedSecretKeys.encryptionPublicKey;
  }

  async balanceTx(tx: UnboundTransaction, ttl: Date = ttlOneHour()): Promise<FinalizedTransaction> {
    const recipe = await this.ctx.wallet.balanceUnboundTransaction(
      tx,
      {
        shieldedSecretKeys: this.ctx.shieldedSecretKeys,
        dustSecretKey: this.ctx.dustSecretKey,
      },
      { ttl },
    );
    const signed = await this.ctx.wallet.signRecipe(recipe, (payload) =>
      this.ctx.unshieldedKeystore.signData(payload),
    );
    return this.ctx.wallet.finalizeRecipe(signed);
  }

  async submitTx(tx: FinalizedTransaction): Promise<string> {
    const id = await this.ctx.wallet.submitTransaction(tx);
    this.logger.info(`submitted ${id}`);
    return id;
  }
}
