/*
 * Registering NIGHT for dust generation.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Adapted from `bboard-cli/src/generate-dust.ts` in midnightntwrk/example-bboard
 * (Copyright (C) Midnight Foundation, Apache-2.0). The HD derivation, keystore
 * construction and registration call are the example's, unchanged in substance.
 *
 * Dust is what actually pays for a transaction, and it is generated by NIGHT
 * that has been registered for the purpose. On the public networks a freshly
 * funded wallet holds NIGHT that is not yet registered, so without this step the
 * first deployment fails at balancing with an error about fees that says nothing
 * about registration. The local standalone node hands out dust directly, which
 * is why only the remote configurations ask for this.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Buffer } from 'node:buffer';

import { getNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { type WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { HDWallet, Roles } from '@midnight-ntwrk/wallet-sdk-hd';
import {
  createKeystore,
  type UnshieldedWalletState,
} from '@midnight-ntwrk/wallet-sdk-unshielded-wallet';
import type { Logger } from 'pino';
import * as Rx from 'rxjs';

export const getUnshieldedSeed = (seed: string): Uint8Array => {
  const hdWalletResult = HDWallet.fromSeed(Buffer.from(seed, 'hex'));
  const { hdWallet } = hdWalletResult as { type: 'seedOk'; hdWallet: HDWallet };

  const derived = hdWallet.selectAccount(0).selectRole(Roles.NightExternal).deriveKeyAt(0);
  if (derived.type === 'keyOutOfBounds') {
    throw new Error('key derivation out of bounds while deriving the unshielded key');
  }
  return derived.key;
};

export const generateDust = async (
  logger: Logger,
  walletSeed: string,
  unshieldedState: UnshieldedWalletState,
  walletFacade: WalletFacade,
): Promise<string | undefined> => {
  const dustState = await walletFacade.dust.waitForSyncedState();
  const keystore = createKeystore(getUnshieldedSeed(walletSeed), getNetworkId());
  const utxos = unshieldedState.availableCoins.filter(
    (coin) => !coin.meta.registeredForDustGeneration,
  );

  if (utxos.length === 0) {
    logger.debug('every NIGHT UTXO is already registered for dust generation');
    return undefined;
  }

  const recipe = await walletFacade.registerNightUtxosForDustGeneration(
    utxos,
    keystore.getPublicKey(),
    (payload) => keystore.signData(payload),
    dustState.address,
  );
  const transaction = await walletFacade.finalizeRecipe(recipe);
  const txId = await walletFacade.submitTransaction(transaction);

  // Waiting for a non-zero balance rather than returning on submission: the
  // next thing the operator does is deploy, and deploying before dust exists
  // fails in a way that looks like a bug in the contract.
  await Rx.firstValueFrom(
    walletFacade.state().pipe(Rx.filter((state) => state.dust.balance(new Date()) > 0n)),
  );

  logger.info({ txId }, 'registered NIGHT for dust generation');
  return txId;
};
